<!DOCTYPE html>
<!-- saved from url=(0050)http://getbootstrap.com/examples/navbar-fixed-top/ -->
<html lang="ru"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Fixed Top Navbar Example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/navbar-fixed-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
      
      
      
      
      
<?php

  $mysqli = new mysqli('newhtf.localhost', 'root', 'projects', 'newhtf');
  if (mysqli_connect_errno()) {
    echo "Подключение невозможно: ".mysqli_connect_error();
  }
  










if(isset($_GET['id'])) {$category_id = $_GET['id'];}
if(isset($_GET['hid'])) {$hid = $_GET['hid'];}
if(isset($_GET['gid'])) {$gid = $_GET['gid'];}




$mybasecat = mysql_query("SELECT `id`,`cat_name`,`cat_pic` FROM `categories` WHERE `parent_id`='0'",$db) or die(mysql_error());
if (mysql_num_rows($mybasecat) > 0)
{
	$myrowcat = mysql_fetch_array($mybasecat);
	do { 

    echo   '<li><a href="cat.php?gid='.$myrowcat['cat_id'].'&cat_id='.$myrowcat['cat_id'].'">'.$myrowcat['cat_name_ru'].'</a></li>';
    
    $mybasecat1 = mysql_query("SELECT `cat_id`,`cat_name` FROM `categories` WHERE (`parent_id`='{$gid}' AND `parent_id`='{$myrowcat['cat_id']}') ORDER BY `cat_id` DESC",$db) or die(mysql_error());
	$myrowcat1 = mysql_fetch_array($mybasecat1);
		if (mysql_num_rows($mybasecat1) > 0)
     	{
				
	    echo	'<ul style="margin: 0px 0px 0px 20px;">';
		
	    do	
	      {
    	      echo	'<li style="height: 10px;"><a style="font-size: 11px;" href="cat.php?gid='.$gid.'&cat_id='.$myrowcat1['cat_id'].'">'.$myrowcat1['cat_name'].'</a></li>';
   		         $mybasecat2 = mysql_query("SELECT `cat_id`,`cat_name` FROM `categories` WHERE (`parent_id`='{$cat_id}' AND `parent_id`='{$myrowcat1['cat_id']}') OR (`parent_id`='{$hid}' AND `parent_id`='{$myrowcat1['cat_id']}') ORDER BY `cat_id` DESC",$db) or die(mysql_error());
		         $myrowcat2 = mysql_fetch_array($mybasecat2);         
  			 if (mysql_num_rows($mybasecat2) > 0)
        	         {
				echo	'<ul style="margin: 0px 0px 0px 40px;">';
					   do
					   {
					    echo '<li style="height: 10px;"><a style="font-size: 11px;" href="cat.php?gid='.$gid.'&hid='.$myrowcat1['cat_id'].'&cat_id='.$myrowcat2['cat_id'].'">'.$myrowcat2['cat_name'].'</a></li>';  
					   }
					   while($myrowcat2 = mysql_fetch_array($mybasecat2));
					   echo '</ul>';
			 }
	      }	
              while($myrowcat1 = mysql_fetch_array($mybasecat1));
	      echo    '<li style="height: 2px;"></li>
		       </ul>';
		
		}
	}
	while($myrowcat = mysql_fetch_array($mybasecat));	
}
else { echo "Нет категорий"; }
$mysqli->close();
?>
      
      
      

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://getbootstrap.com/examples/navbar-fixed-top/#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="http://getbootstrap.com/examples/navbar-fixed-top/#">Home</a></li>
            <li><a href="http://getbootstrap.com/examples/navbar-fixed-top/#about">About</a></li>
            <li><a href="http://getbootstrap.com/examples/navbar-fixed-top/#contact">Contact</a></li>
            <li class="dropdown">
              <a href="http://getbootstrap.com/examples/navbar-fixed-top/#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="http://getbootstrap.com/examples/navbar-fixed-top/#">Action</a></li>
                <li><a href="http://getbootstrap.com/examples/navbar-fixed-top/#">Another action</a></li>
                <li><a href="http://getbootstrap.com/examples/navbar-fixed-top/#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="http://getbootstrap.com/examples/navbar-fixed-top/#">Separated link</a></li>
                <li><a href="http://getbootstrap.com/examples/navbar-fixed-top/#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="http://getbootstrap.com/examples/navbar/">Default</a></li>
            <li><a href="http://getbootstrap.com/examples/navbar-static-top/">Static top</a></li>
            <li class="active"><a href="./Fixed Top Navbar Example for Bootstrap_files/Fixed Top Navbar Example for Bootstrap.html">Fixed top <span class="sr-only">(current)</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Navbar example</h1>
        <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
        <p>To see the difference between static and fixed top navbars, just scroll.</p>
        <p>
          <a class="btn btn-lg btn-primary" href="http://getbootstrap.com/components/#navbar" role="button">View navbar docs »</a>
        </p>
      </div>
 <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Dropdown
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
            </ul>
        </div>
    </div> <!-- /container -->

    
    <div class="btn-group-vertical">
      <button type="button" class="btn btn-default">Кнопка</button>
      <button type="button" class="btn btn-default">Кнопка</button>
      <div class="btn-group">
        <button id="btnGroupVerticalDrop1" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Dropdown
        <span class="caret"></span>
      </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="btnGroupVerticalDrop1">
          <li><a href="#">Dropdown ссылка</a></li>
          <li><a href="#">Dropdown ссылка</a></li>
        </ul>
      </div>
      <button type="button" class="btn btn-default">Кнопка</button>
      <button type="button" class="btn btn-default">Кнопка</button>
      <div class="btn-group open">
        <button id="btnGroupVerticalDrop2" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Dropdown
        <span class="caret"></span>
      </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="btnGroupVerticalDrop2">
          <li><a href="#">Dropdown ссылка</a></li>
          <li><a href="#">Dropdown ссылка</a></li>
        </ul>
      </div>
      <div class="btn-group">
        <button id="btnGroupVerticalDrop3" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Dropdown
        <span class="caret"></span>
      </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="btnGroupVerticalDrop3">
          <li><a href="#">Dropdown ссылка</a></li>
          <li><a href="#">Dropdown ссылка</a></li>
        </ul>
      </div>
      <div class="btn-group">
        <button id="btnGroupVerticalDrop4" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Dropdown
        <span class="caret"></span>
      </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="btnGroupVerticalDrop4">
          <li><a href="#">Dropdown ссылка</a></li>
          <li><a href="#">Dropdown ссылка</a></li>
        </ul>
      </div>
    </div>
    
    
    
<div class="btn-group-vertical">
  ...
</div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="js/ie10-viewport-bug-workaround.js"></script>
  

</body></html>