-- MySQL Script generated by MySQL Workbench
-- 12/13/15 21:48:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema newhtf
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `newhtf` ;

-- -----------------------------------------------------
-- Schema newhtf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newhtf` DEFAULT CHARACTER SET utf8 ;
USE `newhtf` ;

-- -----------------------------------------------------
-- Table `newhtf`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newhtf`.`product` ;

CREATE TABLE IF NOT EXISTS `newhtf`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `price` DOUBLE(10,2) NULL,
  `html` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newhtf`.`product_property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newhtf`.`product_property` ;

CREATE TABLE IF NOT EXISTS `newhtf`.`product_property` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newhtf`.`product_to_property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newhtf`.`product_to_property` ;

CREATE TABLE IF NOT EXISTS `newhtf`.`product_to_property` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `product_property_id` INT NOT NULL,
  `value` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_to_property_product_property_idx` (`product_property_id` ASC),
  INDEX `fk_product_to_property_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_to_property_product_property`
    FOREIGN KEY (`product_property_id`)
    REFERENCES `newhtf`.`product_property` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_to_property_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `newhtf`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
