<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Users</title>
		<link media="screen" rel="stylesheet" type="text/css" href="<?= BASE_URL ?>css/index.css" />
		<link media="screen" rel="stylesheet" type="text/css" href="<?= BASE_URL ?>css/jquery/jquery.ui.css" />
		<script type="text/javascript" src="<?= BASE_URL ?>js/jquery/jquery.js"></script>
	</head>
	<body>