<?php include '_header.phtml'; ?>
<script type="text/javascript" src="<?= BASE_URL ?>js/process.js"></script>
<link media="screen" rel="stylesheet" type="text/css" href="<?= BASE_URL ?>css/process.css" />
<div id="process-panel" bookid="<?= $book_id ?>">
	<div class="progress-bar">
		<div class="progress-bar-color"></div>
		<div class="progress-bar-text"></div>
	</div>
	<div class="clear"></div>
</div>
<?php include '_footer.phtml'; ?>